# Generated by Django 4.2.13 on 2024-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_rename_uuid_transaction_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledwithdrawal',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
