# Generated by Django 4.2.13 on 2024-05-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_scheduledwithdrawal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledwithdrawal',
            old_name='status',
            new_name='settle',
        ),
    ]
