# Generated by Django 4.2.13 on 2024-05-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_rename_status_scheduledwithdrawal_settle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledwithdrawal',
            name='settle',
        ),
        migrations.AddField(
            model_name='transaction',
            name='settle',
            field=models.BooleanField(default=False),
        ),
    ]
