# Generated by Django 4.2.13 on 2024-05-26 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_transaction_bank_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
